### ISSUE TITLE
python setup.py install does not work properly

### ISSUE THREAD

**Issue by eriktaubeneck** [peterruggero/postmaster-python#4]
setup.py has the name of the module name as `'postmaster-python'` but python does not allow for imports of modules with the '-' character in the name. Also, the marketing materials you guys were handing out at Pycon suggests you run `import postmaster`.

This can be fixed by changing line 13 in setup.py to

```
setup(name='postmaster',
```

Also, the package seems to be unavailable on both pip and easy_install under the name `postmaster` but is avaliable under `postmaster-python`. The suggested change should fix this (once synced with the pypi. Once this works, you should edit your README.md to suggest the user runs `pip install postmaster` instead of `easy_install postmaster` since we all know [pip is better than easy_install](http://stackoverflow.com/questions/3220404/why-use-pip-over-easy-install).

**Comment by mentat** [comment]
You are right, we'll update this ASAP.

**Comment by krotkiewicz** [comment]
@eriktaubeneck 

AFAIK the name argument is used by pypi only.
It doesn't have anything in common with package namespace, the package namespace is connected with packages argument.

Example of egg name with dash:
https://github.com/ajford/flask-wtf/

You said that you could install it using easy_install postmaster-python but AFAIK we didn't have our egg in pypi, take a look here: https://pypi.python.org/pypi?%3Aaction=search&term=postmaster-python

Last thing is installing, for me it works fine:
https://gist.github.com/anonymous/3fbe13e407fa00f89f7c

I am using mac os x, maybe on Linux there are some problems ?

**Comment by eriktaubeneck** [comment]
@krotkiewicz 

Also on OS X. Just tried the install again in a new directory and it worked this time. I went back in my terminal session and I think I found the issue. (I ran `python postmaster-python/setup.py install` instead of cding into the dir, and I think that mucked it up.) I also think `easy_install postmaster-python` worked because I had the egg sitting in the dir at that point (doh!). Tried that again and failed with pip and with easy_install.  

Anyways, you may want to change the README.md to 

```
git clone git://github.com/postmaster/postmaster-python.git
cd postmaster-python
python setup.py install
```

until you get it up on pypi.

Cheers guys.

**Comment by mentat** [comment]
Hi all, we've push this to pypi now and changed the name to just "postmaster" instead of "postmaster-python".
